### ISSUE TITLE
Arbitrary crashes when running unit simple tests that just deserialise

### ISSUE THREAD

**Issue by iddm** [Diggsey/ijson#31]
I have the flaky test behaviour, where about 75% of the time those work and pass, and 25% of the time they crash.

I have very simple tests, for example, like this:
```rust
    #[test]
    fn test_unicode_characters() {
        let json = r#""\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0""#;
        let value: IValue = serde_json::from_str(json).expect("IValue parses fine.");
        assert_eq!(
            value.as_string().unwrap(),
            "\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}"
        );

        let json = r#"{"\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0":"\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0"}"#;
        let value: IValue = serde_json::from_str(json).expect("IValue parses fine.");
        assert_eq!(
            value
                .as_object()
                .unwrap()
                .get("\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}")
                .unwrap()
                .as_string()
                .unwrap(),
            "\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}"
        );
    }
```

And I get all sorts of different errors, originating from ijson, which calls std hashmap (hashbrown's), on Rust 1.76.

Usually, all of them happen when deserializing into `IValue`, when the `IValue` object is being dropped when the scope ends, or when I try to locate a value in the `IValue`'s `Object` using the `get` methods.

1:
```
test ivalue_manager::tests::test_unicode_characters ... FAILED

failures:

---- ivalue_manager::tests::test_unicode_characters stdout ----
thread 'ivalue_manager::tests::test_unicode_characters' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:1631:9:
assertion failed: self.is_bucket_full(index)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2:
```
test ivalue_manager::tests::test_unicode_characters ... ok
thread 'ivalue_manager::tests::test_get_memory' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:1177:25:
assertion `left != right` failed
  left: 0
 right: 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:342:17
   3: core::panicking::assert_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:297:5
   4: hashbrown::raw::RawTableInner<A>::find_insert_slot
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:1177:25
   5: hashbrown::raw::RawTable<T,A>::insert
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:740:29
   6: hashbrown::raw::RawTable<T,A>::insert_entry
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:785:18
   7: hashbrown::map::RawVacantEntryMut<K,V,S,A>::insert_hashed_nocheck
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/map.rs:4056:43
   8: hashbrown::map::RawVacantEntryMut<K,V,S,A>::insert
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/map.rs:4016:9
   9: hashbrown::map::RawEntryMut<K,V,S,A>::or_insert_with
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/map.rs:3481:17
  10: hashbrown::set::HashSet<T,S,A>::get_or_insert_with
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/set.rs:979:9
  11: ijson::unsafe_string::IString::intern
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/unsafe_string.rs:196:21
  12: <ijson::unsafe_string::IString as core::convert::From<&str>>::from
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/unsafe_string.rs:282:9
  13: <T as core::convert::Into<U>>::into
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/convert/mod.rs:757:9
  14: <ijson::de::StringVisitor as serde::de::Visitor>::visit_str
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/de.rs:177:12
  15: serde::de::Visitor::visit_borrowed_str
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.171/src/de/mod.rs:1512:9
  16: <serde_json::de::MapKey<R> as serde::de::Deserializer>::deserialize_any
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.109/src/de.rs:2186:39
  17: <serde_json::de::MapKey<R> as serde::de::Deserializer>::deserialize_str
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.171/src/macros.rs:133:13
  18: ijson::de::<impl serde::de::Deserialize for ijson::unsafe_string::IString>::deserialize
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/de.rs:46:9
  19: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.171/src/de/mod.rs:792:9
  20: <serde_json::de::MapAccess<R> as serde::de::MapAccess>::next_key_seed
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.109/src/de.rs:1994:27
  21: serde::de::MapAccess::next_entry_seed
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.171/src/de/mod.rs:1834:20
  22: serde::de::MapAccess::next_entry
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.171/src/de/mod.rs:1884:9
  23: <ijson::de::ObjectVisitor as serde::de::Visitor>::visit_map
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/de.rs:241:34
  24: <ijson::de::ValueVisitor as serde::de::Visitor>::visit_map
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/de.rs:137:9
  25: <&mut serde_json::de::Deserializer<R> as serde::de::Deserializer>::deserialize_any
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.109/src/de.rs:1439:31
  26: ijson::de::<impl serde::de::Deserialize for ijson::value::IValue>::deserialize
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/de.rs:28:9
  27: serde_json::de::from_trait
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.109/src/de.rs:2477:22
  28: serde_json::de::from_str
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.109/src/de.rs:2678:5
  29: project::ivalue_manager::tests::test_get_memory
             at ./src/ivalue_manager.rs:739:21
  30: project::ivalue_manager::tests::test_get_memory::{{closure}}
             at ./src/ivalue_manager.rs:720:25
  31: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  32: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

3:
```
---- ivalue_manager::tests::test_get_memory stdout ----
thread 'ivalue_manager::tests::test_get_memory' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:174:9:
Went past end of probe sequence
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: hashbrown::raw::ProbeSeq::move_next
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:174:9
   3: hashbrown::raw::RawTableInner<A>::find_inner
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:1212:13
   4: hashbrown::raw::RawTable<T,A>::find
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:838:22
   5: hashbrown::raw::RawTable<T,A>::remove_entry
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/raw/mod.rs:595:15
   6: hashbrown::map::HashMap<K,V,S,A>::remove_entry
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/map.rs:1970:9
   7: hashbrown::map::HashMap<K,V,S,A>::remove
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/map.rs:1931:15
   8: hashbrown::set::HashSet<T,S,A>::remove
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hashbrown-0.13.2/src/set.rs:1192:9
   9: ijson::unsafe_string::IString::drop_impl
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/unsafe_string.rs:253:21
  10: <ijson::value::IValue as core::ops::drop::Drop>::drop
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/value.rs:727:34
  11: core::ptr::drop_in_place<ijson::value::IValue>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
  12: core::ptr::drop_in_place<ijson::unsafe_string::IString>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
  13: core::ptr::drop_in_place<(ijson::unsafe_string::IString,ijson::value::IValue)>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
  14: ijson::object::HeaderMut::clear
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/object.rs:261:27
  15: ijson::object::IObject::clear
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/object.rs:679:17
  16: ijson::object::IObject::drop_impl
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/object.rs:777:9
  17: <ijson::value::IValue as core::ops::drop::Drop>::drop
             at /root/.cargo/git/checkouts/ijson-51de9a23b0d73f7a/e0119ac/src/value.rs:726:34
  18: core::ptr::drop_in_place<ijson::value::IValue>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
  19: project::ivalue_manager::tests::test_get_memory
             at ./src/ivalue_manager.rs:742:5
  20: project::ivalue_manager::tests::test_get_memory::{{closure}}
             at ./src/ivalue_manager.rs:720:25
  21: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  22: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    ivalue_manager::tests::test_get_memory

test result: FAILED. 15 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.08s
```

4:
```
error: test failed, to rerun pass `-p project --lib`

Caused by:
  process didn't exit successfully: `/build/project/bin/linux-x64-release/target/debug/deps/project-61d5d5864c506beb` (signal: 11, SIGSEGV: invalid memory reference)
```

Is this coming from `ijson`'s code incorrectly using the hashmap, is it coming from the `std/hashbrown` hashmap implementation, or is this a bug in Rustc? I am trying to figure out the latter, while the first two questions need a deeper research.

**Comment by Diggsey** [comment]
Are you running the tests with `-- --test-threads=1` ?

**Comment by iddm** [comment]
> I tried to reproduce this issue:
> 
>     * I switched to Rust 1.76
> 
>     * I created a new binary crate with the code you provided:
> 
> 
> ```rust
> use ijson::IValue;
> 
> fn main() {}
> 
> #[test]
> fn test_unicode_characters() {
>     let json = r#""\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0""#;
>     let value: IValue = serde_json::from_str(json).expect("IValue parses fine.");
>     assert_eq!(
>         value.as_string().unwrap(),
>         "\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}"
>     );
> 
>     let json = r#"{"\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0":"\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0"}"#;
>     let value: IValue = serde_json::from_str(json).expect("IValue parses fine.");
>     assert_eq!(
>         value
>             .as_object()
>             .unwrap()
>             .get("\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}")
>             .unwrap()
>             .as_string()
>             .unwrap(),
>         "\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}\u{a0}"
>     );
> }
> ```
> 
>     * I ran `cargo test` a bunch of times and `cargo test --release`.
> 
> 
> Neither of these caused a panic.
> 
> Are you able to reproduce the issue with these steps?

Yes. It doesn't happen every time; as I said, it is flaky. I run `cargo test` a few times immediately after the previous run finished, until it crashes. The way I found this problem was a CI failure, where it also crashed and led me to start the investigation.

Running the unit tests via `cargo test` on this repository (the latest master), also is flaky: rarely does it produce the "all passed" output, usually it fails, with one, two, four or more tests, the example of the errors:

```

---- object::tests::can_insert stdout ----
thread 'object::tests::can_insert' panicked at /home/fx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mockalloc-0.1.2/src/lib.rs:434:21:
called `Result::unwrap()` on an `Err` value: Leak
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- object::tests::can_nest stdout ----
thread 'object::tests::can_nest' panicked at /home/fx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mockalloc-0.1.2/src/lib.rs:434:21:
called `Result::unwrap()` on an `Err` value: DoubleFree
```

**Comment by iddm** [comment]
> Are you running the tests with `-- --test-threads=1` ?
> 
> edit: Sorry I see you mean your own test, not the ijson tests themselves.

I apologise, I overlooked this message. Should we only run the tests single-threaded?

**Comment by Diggsey** [comment]
> I apologise; I overlooked this message. Should we only run the tests single-threaded?

The tests in this repo should not be run concurrently - that's because I use a custom allocator to track allocations and deallocations during tests to ensure that there are no memory leaks. Note that even when run with `--test-threads=1` individual tests may still use multiple threads, it just prevents two tests from running at the same time in the same process, which would mess up the allocation tracking.

> Which parts exactly are not thread-safe here?

Only the allocation tracker is not thread-safe, nothing in ijson itself is not thread-safe.

> I cannot force my code to avoid running tests in parallel

This should not be required for your own tests unless you are also using `mockalloc` to track allocations.

**Comment by Diggsey** [comment]
> It happens in CI, on my local ArchLinux x86-64 desktop, and on M1 Pro. I don't think this is related to the environment.

The factors I would like to eliminate are:
- Some other code or test in your test suite is causing the issue. If you create a new binary crate with *only* the code you gave as the reproduction example, are you still able to reproduce it?
- OS - you mentioned that your reproduced it on both an M1 Pro, and ArchLinux x86-64, but it's not clear whether you were talking about the issues with ijson's test suite (which are caused when you run with multiple test threads) or your original test suite.

**Comment by iddm** [comment]
> > I apologise; I overlooked this message. Should we only run the tests single-threaded?
> 
> The tests in this repo should not be run concurrently - that's because I use a custom allocator to track allocations and deallocations during tests to ensure that there are no memory leaks. Note that even when run with `--test-threads=1` individual tests may still use multiple threads, it just prevents two tests from running at the same time in the same process, which would mess up the allocation tracking.
> 
> > Which parts exactly are not thread-safe here?
> 
> Only the allocation tracker is not thread-safe, nothing in ijson itself is not thread-safe.
> 
> > I cannot force my code to avoid running tests in parallel
> 
> This should not be required for your own tests unless you are also using `mockalloc` to track allocations.

Okay, let's pause for now! I think I know what's the issue, I forgot we actually use a fork of this project! I sincerely apologise for possibly a false alarm!
